// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwRULvSkapc_oRa4vbgyVm5Ywb04pvhIE',
    appId: '1:538648618303:web:1503bcae2f0757a97bdf8a',
    messagingSenderId: '538648618303',
    projectId: 'askute-a93f5',
    authDomain: 'askute-a93f5.firebaseapp.com',
    storageBucket: 'askute-a93f5.appspot.com',
    measurementId: 'G-8TDDHRD81N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDiKA4ovU6d1003gr7jHIMBs8ejUgl6aPQ',
    appId: '1:538648618303:android:7b297b6eb1351c417bdf8a',
    messagingSenderId: '538648618303',
    projectId: 'askute-a93f5',
    storageBucket: 'askute-a93f5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBUZ7O2LeXGDfg43joz-PeBrZKn7VuLpO8',
    appId: '1:538648618303:ios:97b1020528d8ef987bdf8a',
    messagingSenderId: '538648618303',
    projectId: 'askute-a93f5',
    storageBucket: 'askute-a93f5.appspot.com',
    iosBundleId: 'com.example.askute',
  );
}
